# Author: R.Lisovenko
# Date: 21.09.2026
# Description: Base SQL Server 2025 image for the UDC environment.

# Use the official Microsoft SQL Server 2025 image as the base image.
FROM mcr.microsoft.com/mssql/server:2025-latest